/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemausuarios;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.xmlrpc.XmlRpcException;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;

/**
 *
 * @author freddy
 */

public class Usuarios extends javax.swing.JFrame {

    //static XmlRpcClient client = null;
        static ArrayList<String> Linea=new ArrayList();

    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        registrar = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        credito = new javax.swing.JTextField();
        actual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crear = new javax.swing.JButton();
        comboVuelos2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        prue2 = new javax.swing.JTextField();
        pru = new javax.swing.JTextField();
        prue3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        salida = new javax.swing.JTextField();
        llegada = new javax.swing.JTextField();
        horaS = new javax.swing.JTextField();
        horaLL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comboVuelos = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboAero = new javax.swing.JComboBox();
        veraero = new javax.swing.JButton();
        verVuel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        VerUsuariosVuelos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USUARIOS");
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(897, 610));
        setPreferredSize(new java.awt.Dimension(895, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrar.setBackground(new java.awt.Color(0, 0, 0));
        registrar.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel1.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 230, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 230, -1));
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 230, -1));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 230, -1));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 230, -1));
        jPanel1.add(credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 230, -1));

        actual.setEditable(false);
        jPanel1.add(actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 230, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Dirección Actual:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Nombre de Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("No. Tarjeta de Credito:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Teléfono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        jTabbedPane1.addTab("CREAR USUARIOS", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crear.setBackground(new java.awt.Color(0, 0, 0));
        crear.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        crear.setForeground(new java.awt.Color(255, 255, 255));
        crear.setText("REGISTRAR");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel2.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, -1));

        comboVuelos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVuelos2ActionPerformed(evt);
            }
        });
        jPanel2.add(comboVuelos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 220, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Vuelos:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Categoria:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 20));

        prue2.setEditable(false);
        jPanel2.add(prue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 240, -1));

        pru.setEditable(false);
        jPanel2.add(pru, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 240, -1));

        prue3.setEditable(false);
        jPanel2.add(prue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 240, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primera Clase", "Clase Turista", "Clase Ejecutiva" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 220, -1));

        salida.setEditable(false);
        jPanel2.add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 160, -1));

        llegada.setEditable(false);
        jPanel2.add(llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 160, -1));

        horaS.setEditable(false);
        jPanel2.add(horaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 160, -1));

        horaLL.setEditable(false);
        jPanel2.add(horaLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 160, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Salida:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("LLegada");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Hora Salida:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("Hora LLegada");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asignar_vuelo.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        jTabbedPane1.addTab("ASIGNACION DE VUELOS", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVuelosActionPerformed(evt);
            }
        });
        jPanel3.add(comboVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 280, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Vuelos:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("Aeropuertos:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        comboAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAeroActionPerformed(evt);
            }
        });
        jPanel3.add(comboAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 200, -1));

        veraero.setBackground(new java.awt.Color(0, 0, 0));
        veraero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        veraero.setForeground(new java.awt.Color(255, 255, 255));
        veraero.setText("VER AEROPUERTOS");
        veraero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veraeroActionPerformed(evt);
            }
        });
        jPanel3.add(veraero, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        verVuel.setBackground(new java.awt.Color(0, 0, 0));
        verVuel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        verVuel.setForeground(new java.awt.Color(255, 255, 255));
        verVuel.setText("VER VUELOS");
        verVuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verVuelActionPerformed(evt);
            }
        });
        jPanel3.add(verVuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/observar_Vuelos.jpg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("OBSERVACION DE VUELOS", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerUsuariosVuelos.setBackground(new java.awt.Color(0, 0, 0));
        VerUsuariosVuelos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        VerUsuariosVuelos.setForeground(new java.awt.Color(255, 255, 255));
        VerUsuariosVuelos.setText("Ver Usuarios Vuelos");
        VerUsuariosVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerUsuariosVuelosActionPerformed(evt);
            }
        });
        jPanel4.add(VerUsuariosVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Vuelo", "Salida", "LLegada", "Hora Salida", "Hora LLegada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 580, 320));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/observar_Vuelos.jpg"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("LISTADO DE VUELOS", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int contador=0;
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
     
        String nom=nombre.getText().trim();
        String cont=contraseña.getText().trim();
        String usua=usuario.getText().trim();
        String dir=direccion.getText().trim();
        String tel=telefono.getText().trim();
        String cred=credito.getText();
        String dirActual=actual.getText().trim();
        
        System.out.println(nom+","+cont+","+","+usua+","+dir+","+","+tel+","+cred+","+","+dirActual);

          XmlRpcClient client = null;
        
            try { 
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
           
           contador++;
           String conta=String.valueOf(contador);
           System.out.println("cont1: "+conta);
           config.setServerURL(new URL("http://localhost:9000"));
           client=new XmlRpcClient();
           client.setConfig(config);
         
           
           Object[] paramsavl = new Object[]{usua};
            String datoavl=(String) client.execute("sins",paramsavl);           
           System.out.println(datoavl);
           
           Object[] parametrosUsuario = new Object[]{conta,nom,cont,usua,dir,tel,cred};
           String dato=(String) client.execute("ListaDoble",parametrosUsuario);
                System.out.println("datos: "+dato);
          
          
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_registrarActionPerformed

    int contador2=0;
    String cont="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 
            XmlRpcClient client = null;
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();

           contador2+=1;

           config.setServerURL(new URL("http://localhost:9000"));
                    
           client=new XmlRpcClient();
           client.setConfig(config);
         
           
            cont=String.valueOf(contador2);
            System.out.println("contador2: "+cont);
            Object[] params4 = new Object[]{"1040"};
            String dato2=(String) client.execute("MostrarListaCategoria",params4);
            System.out.println(dato2);
           
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    ArrayList<String> aeros=new ArrayList();
    ArrayList<String> vuelosaero=new ArrayList();
    ArrayList<String> vueloEstado=new ArrayList();
    private void veraeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veraeroActionPerformed
         
        comboAero.removeAllItems();
        try { 
            XmlRpcClient client = null;
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();


           config.setServerURL(new URL("http://localhost:9000"));
                    
           client=new XmlRpcClient();
           client.setConfig(config);
         
           for(int i=1;i<=100;i++){
            String cont2=String.valueOf(i);
            System.out.println("contador2: "+cont2);
            Object[] params4 = new Object[]{cont2};
            String dato2=(String) client.execute("MostrarListaAero",params4);
            //String dato3=(String) client.execute("MostrarListaVuelo",params4);
            //String dato4=(String) client.execute("MostrarVueloAero",params4);
            //String dato5=(String) client.execute("MostrarEstadoVuelo",params4);
            //aeros.add(dato4);
          //  vuelosaero.add(dato3);
            //vueloEstado.add(dato5);
            comboAero.addItem(dato2);
            //comboAero2.addItem(dato2);
            //comboVuelos.addItem(dato3+"  Estado: "+dato5);
            //comboVuelos2.addItem(dato3);
            
           }
           
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_veraeroActionPerformed

    private void comboVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVuelosActionPerformed
       
    }//GEN-LAST:event_comboVuelosActionPerformed
    private void comboAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAeroActionPerformed
      
    }//GEN-LAST:event_comboAeroActionPerformed

    private void comboVuelos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVuelos2ActionPerformed
              try { 
            XmlRpcClient client = null;
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();


           config.setServerURL(new URL("http://localhost:9000"));
                    
           client=new XmlRpcClient();
           client.setConfig(config);
         

            Object[] params4 = new Object[]{comboVuelos2.getSelectedItem().toString()};
            String dato2=(String) client.execute("MostrarAeropuertoDeVuelos",params4);
            String dato3=(String) client.execute("MostrarListaCategoria",params4);
            String dato4=(String) client.execute("MostrarListaCategoria2",params4);
            String dato5=(String) client.execute("MostrarListaCategoria3",params4);          
            String dato6=(String) client.execute("MostrarAeroVuelosHoraS",params4);
            String dato7=(String) client.execute("MostrarAeroVuelosHoraLL",params4); 
            String dato8=(String) client.execute("MostrarAeroVuelosSalida",params4);
            //aeros.add(dato4);
          //  vuelosaero.add(dato3);
            //vueloEstado.add(dato5);
              actual.setText(dato2);
              salida.setText(dato8);
              llegada.setText(dato2);
              horaS.setText(dato6);
              horaLL.setText(dato7);
              pru.setText(dato3);
              prue2.setText(dato4);
              prue3.setText(dato5);
            //comboAero2.addItem(dato2);
            //comboVuelos.addItem(dato3+"  Estado: "+dato5);
            //comboVuelos2.addItem(dato3);
            
           
           
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }        
    }//GEN-LAST:event_comboVuelos2ActionPerformed

    private void verVuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verVuelActionPerformed
       comboVuelos.removeAllItems();
       comboVuelos2.removeAllItems();
        try { 
            XmlRpcClient client = null;
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();


           config.setServerURL(new URL("http://localhost:9000"));
                    
           client=new XmlRpcClient();
           client.setConfig(config);
         
           for(int i=1;i<=100;i++){
            String cont2=String.valueOf(i);
            System.out.println("contador2: "+cont2);
            Object[] params4 = new Object[]{cont2};
           // String dato2=(String) client.execute("MostrarListaAero",params4);
            String dato3=(String) client.execute("MostrarListaVuelo",params4);
            //String dato4=(String) client.execute("MostrarVueloAero",params4);
            String dato5=(String) client.execute("MostrarEstadoVuelo",params4);
            //aeros.add(dato4);
          //  vuelosaero.add(dato3);
            //vueloEstado.add(dato5);
            //comboAero.addItem(dato2);
            //comboAero2.addItem(dato2);
            comboVuelos.addItem(dato3+"  Estado: "+dato5);
            comboVuelos2.addItem(dato3);
            
           }
           
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_verVuelActionPerformed

    int co=0;
    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed

        
        
        XmlRpcClient client = null;
        
            try { 
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
           
           co++;
           String conta=String.valueOf(co);
           System.out.println("cont1: "+conta);
           config.setServerURL(new URL("http://localhost:9000"));
           client=new XmlRpcClient();
           client.setConfig(config);
                   
           Object[] parametrosVuelo = new Object[]{conta,nombre.getText().trim(),comboVuelos2.getSelectedItem().toString(),salida.getText(),llegada.getText(),horaS.getText(),horaLL.getText()};
           String dato=(String) client.execute("UsuariosVuelos",parametrosVuelo);
           
        
          
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }   
    }//GEN-LAST:event_crearActionPerformed

    private void VerUsuariosVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerUsuariosVuelosActionPerformed
           try { 
            XmlRpcClient client = null;
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();


           config.setServerURL(new URL("http://localhost:9000"));
                    
           client=new XmlRpcClient();
           client.setConfig(config);
          jTable1.getTableHeader().setReorderingAllowed(false) ;

        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
        Object [] filas=new Object[modelo.getColumnCount()];
             
        
         for(int i=1;i<=100;i++){
             String cont=String.valueOf(i);
            Object[] params4 = new Object[]{cont};
            String dato2=(String) client.execute("MostrarUsuariosVuelos",params4);
            String dato3=(String) client.execute("MostrarUsuariosVuelosVuelo",params4);
            String dato4=(String) client.execute("MostrarUsuariosVuelosSalida",params4);
            String dato5=(String) client.execute("MostrarUsuariosVuelosLLegada",params4);
            String dato6=(String) client.execute("MostrarUsuarioVueloHoraS",params4);
            String dato7=(String) client.execute("MostrarUsuarioVueloHoraLL",params4);
            
             System.out.println(dato2);
            filas[0]=dato2;
            filas[1]=dato3;
            filas[2]=dato4;
            filas[3]=dato5;
            filas[4]=dato6;
            filas[5]=dato7;
        //combo.addItem(nom);
        modelo.addRow(filas);
         }
           
           
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }   
    }//GEN-LAST:event_VerUsuariosVuelosActionPerformed
        
    /**
     * @param args the command line arguments
     */                

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
                
   
      /*  try { 
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
                    try {
                        config.setServerURL(new URL("http://localhost:9000"));
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }
    client=new XmlRpcClient();
    client.setConfig(config);
    Object[] params = new Object[]{150, 100};
    Object[] params3 = new Object[]{"Alejandro"};
    Integer result = (Integer) client.execute("suma", params);
            System.out.println("Suma: "+result);
    String [] params2 = new String[1];
    params2[0]="FREDDY ALEJANRO MONTERROS";
    String dato=(String) client.execute("list_contents",params3);
            System.out.println("Datos: "+dato);
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}
     */
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerUsuariosVuelos;
    private javax.swing.JTextField actual;
    private javax.swing.JComboBox comboAero;
    private javax.swing.JComboBox comboVuelos;
    private javax.swing.JComboBox comboVuelos2;
    private javax.swing.JTextField contraseña;
    private javax.swing.JButton crear;
    private javax.swing.JTextField credito;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField horaLL;
    private javax.swing.JTextField horaS;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField llegada;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pru;
    private javax.swing.JTextField prue2;
    private javax.swing.JTextField prue3;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField salida;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField usuario;
    private javax.swing.JButton verVuel;
    private javax.swing.JButton veraero;
    // End of variables declaration//GEN-END:variables
}
