
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.xmlrpc.XmlRpcException;
import org.apache.xmlrpc.client.XmlRpcClient;
import org.apache.xmlrpc.client.XmlRpcClientConfigImpl;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author freddy
 */
public class Vuelos extends javax.swing.JFrame {

    /**
     * Creates new form Vuelos
     */
    public Vuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        CrearAero = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboAero2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        llegada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Lsalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        horaS = new javax.swing.JTextField();
        horaLL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ident = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        primera = new javax.swing.JLabel();
        primeraPasajero = new javax.swing.JTextField();
        primeraCosto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        turista = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        turistaCosto = new javax.swing.JTextField();
        turistaPasajero = new javax.swing.JTextField();
        ejecutiva = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ejecutivaCosto = new javax.swing.JTextField();
        ejecutivaPasajero = new javax.swing.JTextField();
        crearVuelo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(897, 610));
        setPreferredSize(new java.awt.Dimension(895, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(885, 571));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(885, 571));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 240, -1));
        jPanel1.add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 240, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 240, -1));

        CrearAero.setBackground(new java.awt.Color(0, 0, 0));
        CrearAero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CrearAero.setForeground(new java.awt.Color(255, 255, 255));
        CrearAero.setText("REGISTRAR");
        CrearAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearAeroActionPerformed(evt);
            }
        });
        jPanel1.add(CrearAero, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Pais:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aeropuerto.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        jTabbedPane1.addTab("CREAR AEROPUERTOS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboAero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAero2ActionPerformed(evt);
            }
        });
        jPanel2.add(comboAero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Aeropuerto:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
        jPanel2.add(llegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 260, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Lugar de Llegada:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        Lsalida.setEditable(false);
        Lsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LsalidaActionPerformed(evt);
            }
        });
        jPanel2.add(Lsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 260, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Lugar de Salida:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel2.add(horaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 260, -1));
        jPanel2.add(horaLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 260, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Hora de Salida:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Hora de LLegada:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        ident.setEditable(false);
        jPanel2.add(ident, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 170, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("ID:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        primera.setBackground(new java.awt.Color(204, 204, 255));
        primera.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        primera.setForeground(new java.awt.Color(0, 0, 204));
        primera.setText("Primera Clase");
        jPanel2.add(primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));
        jPanel2.add(primeraPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 160, -1));
        jPanel2.add(primeraCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 140, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Cantidad Pasajeros:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Costo:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        turista.setBackground(new java.awt.Color(204, 204, 255));
        turista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        turista.setForeground(new java.awt.Color(0, 51, 153));
        turista.setText("Clase Turista");
        jPanel2.add(turista, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("Cantidad Pasajeros:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Costo:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, -1, -1));
        jPanel2.add(turistaCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 140, -1));

        turistaPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turistaPasajeroActionPerformed(evt);
            }
        });
        jPanel2.add(turistaPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 160, -1));

        ejecutiva.setBackground(new java.awt.Color(204, 204, 255));
        ejecutiva.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ejecutiva.setForeground(new java.awt.Color(0, 0, 204));
        ejecutiva.setText("Clase Ejecutiva");
        jPanel2.add(ejecutiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Cantidad Pasajeros:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Costo:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));
        jPanel2.add(ejecutivaCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 140, -1));
        jPanel2.add(ejecutivaPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 160, -1));

        crearVuelo.setBackground(new java.awt.Color(0, 0, 0));
        crearVuelo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        crearVuelo.setForeground(new java.awt.Color(255, 255, 255));
        crearVuelo.setText("REGISTRAR");
        crearVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearVueloActionPerformed(evt);
            }
        });
        jPanel2.add(crearVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vuelos.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        jTabbedPane1.addTab("CREAR VUELOS", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int contador=0;
    private void CrearAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearAeroActionPerformed
        String nom=nombre.getText().trim();
        String pa=pais.getText().trim();
        String contrase=contraseña.getText().trim();
        
        comboAero2.addItem(nom);
        
        XmlRpcClient client = null;
        
            try { 
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
           
           contador++;
           String conta=String.valueOf(contador);
           System.out.println("cont1: "+conta);
           config.setServerURL(new URL("http://localhost:9000"));
           client=new XmlRpcClient();
           client.setConfig(config);
                   
           Object[] parametrosUsuario = new Object[]{conta,nom,pa,contrase};
           String dato=(String) client.execute("ListaAeropuerto",parametrosUsuario);
                System.out.println("datos: "+dato);
          
          
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Vuelos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_CrearAeroActionPerformed
    int contador2=0;
    String cont="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             try { 
            XmlRpcClient client = null;
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();

           contador2+=1;

           config.setServerURL(new URL("http://localhost:9000"));
                    
           client=new XmlRpcClient();
           client.setConfig(config);
         
           
            cont=String.valueOf(contador2);
            System.out.println("contador2: "+cont);
            Object[] params4 = new Object[]{cont};
            String dato2=(String) client.execute("MostrarListaVuelo",params4);
            System.out.println(dato2);
           
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Vuelos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LsalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LsalidaActionPerformed

    private void turistaPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turistaPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turistaPasajeroActionPerformed
    int contador3=0;
    private void crearVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearVueloActionPerformed
         String aerop=comboAero2.getSelectedItem().toString();
         String id=ident.getText().trim();
         String salida=Lsalida.getText().trim();
         String llega=llegada.getText().trim();
         String hSalida=horaS.getText().trim();
         String hLLegada=horaLL.getText().trim();
         
        XmlRpcClient client = null;
        
            try { 
	    // Generar el Cliente 
	   XmlRpcClientConfigImpl config = new XmlRpcClientConfigImpl();
           
           contador3++;
           String conta=String.valueOf(contador3);
           System.out.println("cont1: "+conta);
           config.setServerURL(new URL("http://localhost:9000"));
           client=new XmlRpcClient();
           client.setConfig(config);
                   
           Object[] parametrosVuelo = new Object[]{conta,id,aerop,salida,llega,hSalida,hLLegada};
           String dato=(String) client.execute("ListaVuelos",parametrosVuelo);

           
           if(primera.getText().trim().equals("Primera Clase")){
               Object[] parametrosCategoria = new Object[]{id,primera.getText().trim(),primeraPasajero.getText().trim(),primeraCosto.getText().trim()};
               String dato2=(String) client.execute("ListaCategoria",parametrosCategoria);
           }
           if(turista.getText().trim().equals("Clase Turista")){
               Object[] parametrosCategoria = new Object[]{id,turista.getText().trim(),turistaPasajero.getText().trim(),turistaCosto.getText().trim()};
               String dato2=(String) client.execute("ListaCategoria",parametrosCategoria);  
           }
           if(ejecutiva.getText().trim().equals("Clase Turista")){
               Object[] parametrosCategoria = new Object[]{id,ejecutiva.getText().trim(),ejecutiva.getText().trim(),ejecutiva.getText().trim()};
               String dato2=(String) client.execute("ListaCategoria",parametrosCategoria);  
           }
           
          
          
        } catch (XmlRpcException e) { 
	    System.out.println("Error en XML-RPC: " + e.getMessage());
	}   catch (MalformedURLException ex) {
                Logger.getLogger(Vuelos.class.getName()).log(Level.SEVERE, null, ex);
            }              
    }//GEN-LAST:event_crearVueloActionPerformed

    int contadorID=1010;
    private void comboAero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAero2ActionPerformed
        
        contadorID+=15;
        
        ident.setText(String.valueOf(contadorID));
        Lsalida.setText(comboAero2.getSelectedItem().toString());
        
    }//GEN-LAST:event_comboAero2ActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vuelos().setVisible(true);
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearAero;
    private javax.swing.JTextField Lsalida;
    private javax.swing.JComboBox comboAero2;
    private javax.swing.JTextField contraseña;
    private javax.swing.JButton crearVuelo;
    private javax.swing.JLabel ejecutiva;
    private javax.swing.JTextField ejecutivaCosto;
    private javax.swing.JTextField ejecutivaPasajero;
    private javax.swing.JTextField horaLL;
    private javax.swing.JTextField horaS;
    private javax.swing.JTextField ident;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField llegada;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pais;
    private javax.swing.JLabel primera;
    private javax.swing.JTextField primeraCosto;
    private javax.swing.JTextField primeraPasajero;
    private javax.swing.JLabel turista;
    private javax.swing.JTextField turistaCosto;
    private javax.swing.JTextField turistaPasajero;
    // End of variables declaration//GEN-END:variables
}
